/* ===========================================================================
   CATÁLOGO DE LA WEB — selección curada de los productos más vendibles.
   Las fotos reales se añaden después (campo `image`); mientras tanto cada
   producto tiene un `hue` que genera un mosaico holográfico coherente.
   El catálogo completo de 150 productos vive en /docs/CATALOGO-150-PRODUCTOS.md

   Nota de honestidad: `proof` son etiquetas editoriales (tendencia), NO cifras
   de ventas inventadas. `compareAt` es el PVP de mercado de referencia.
   =========================================================================== */

export type Badge =
  | "VIRAL"
  | "TOP VENTAS"
  | "NUEVO"
  | "EDICIÓN LIMITADA"
  | "TRENDING";

export type CategoryKey =
  | "iluminacion"
  | "tech"
  | "hogar"
  | "selfcare"
  | "accesorios";

export interface Product {
  id: string;
  name: string;
  category: CategoryKey;
  price: number;
  compareAt?: number;
  tagline: string;
  badge?: Badge;
  hue: number; // matiz base del mosaico holográfico
  rating: number; // 4.0 - 5.0
  proof: string; // etiqueta editorial honesta (no inventamos ventas)
  featured?: boolean;
  bestSeller?: boolean; // "producto del mes" destacado en la home
  image?: string; // ruta a foto real cuando exista
  seo?: string; // descripción SEO (meta) para buscadores
}

export interface Category {
  key: CategoryKey;
  name: string;
  blurb: string;
  hue: number;
  image: string;
}

export const CATEGORIES: Category[] = [
  { key: "iluminacion", name: "Iluminación", blurb: "Tu cuarto, otra dimensión.", hue: 265, image: "/productos/proyector-galaxia-aurora.jpg" },
  { key: "tech", name: "Tech & Gadgets", blurb: "Lo que no sabías que necesitabas.", hue: 210, image: "/productos/pixel-clock.jpg" },
  { key: "hogar", name: "Hogar Aesthetic", blurb: "Para un feed de revista.", hue: 320, image: "/productos/espejo-hollywood.jpg" },
  { key: "selfcare", name: "Self-care", blurb: "Glow-up sin salir de casa.", hue: 175, image: "/productos/gua-sha-set.jpg" },
  { key: "accesorios", name: "Accesorios", blurb: "El detalle que lo cambia todo.", hue: 290, image: "/productos/tote-holografico.jpg" },
];

export const CATEGORY_MAP: Record<CategoryKey, Category> = Object.fromEntries(
  CATEGORIES.map((c) => [c.key, c]),
) as Record<CategoryKey, Category>;

const RAW_PRODUCTS: Product[] = [
  // — Iluminación —
  { id: "proyector-galaxia-aurora", name: "Proyector Galaxia Aurora", category: "iluminacion", price: 34.99, compareAt: 59.99, tagline: "Convierte tu techo en una galaxia entera.", badge: "VIRAL", hue: 262, rating: 4.9, proof: "Viral en TikTok", featured: true, bestSeller: true },
  { id: "astronauta-nebulosa", name: "Astronauta Proyector Nebulosa", category: "iluminacion", price: 39.99, tagline: "El astronauta que flota en tu nebulosa privada.", badge: "TOP VENTAS", hue: 248, rating: 4.8, proof: "Top de la semana", featured: true },
  { id: "tira-led-reactiva", name: "Tira LED RGB Reactiva 10m", category: "iluminacion", price: 24.99, compareAt: 39.99, tagline: "Baila al ritmo de tu música. Literalmente.", badge: "VIRAL", hue: 200, rating: 4.7, proof: "Lo más guardado", featured: true },
  { id: "lampara-luna-levitante", name: "Lámpara Luna Levitante", category: "iluminacion", price: 49.99, tagline: "Una luna real flotando sobre tu mesa.", badge: "EDICIÓN LIMITADA", hue: 280, rating: 4.9, proof: "Edición limitada" },
  { id: "lampara-sunset", name: "Lámpara Atardecer Sunset", category: "iluminacion", price: 18.99, tagline: "El atardecer perfecto para tus fotos, a demanda.", badge: "TRENDING", hue: 330, rating: 4.6, proof: "Tendencia 2026" },
  { id: "pixel-clock", name: "Cubo Pixel Reloj LED", category: "iluminacion", price: 27.99, tagline: "Reloj, clima y pixel art en tu escritorio.", badge: "NUEVO", hue: 215, rating: 4.7, proof: "Recién llegado" },

  // — Tech & Gadgets —
  { id: "mini-impresora-termica", name: "Mini Impresora Térmica", category: "tech", price: 36.99, compareAt: 54.99, tagline: "Imprime memes y fotos sin tinta. Cabe en el bolsillo.", badge: "VIRAL", hue: 258, rating: 4.8, proof: "Viral en TikTok", featured: true },
  { id: "auriculares-open-ear", name: "Auriculares Open-Ear Air", category: "tech", price: 29.99, tagline: "Música y mundo a la vez. El clip que petó.", badge: "TRENDING", hue: 195, rating: 4.6, proof: "Tendencia 2026", featured: true },
  { id: "smart-ring", name: "Anillo Inteligente Smart Ring", category: "tech", price: 54.99, tagline: "Cuenta tu sueño y tus pasos. Sin pantalla, pura magia.", badge: "NUEVO", hue: 238, rating: 4.5, proof: "Recién llegado" },
  { id: "ventilador-cuello", name: "Ventilador de Cuello Bladeless", category: "tech", price: 19.99, tagline: "Aire fresco manos libres. Verano resuelto.", hue: 188, rating: 4.5, proof: "El más buscado" },
  { id: "teclado-mini-pastel", name: "Teclado Mecánico Mini Pastel", category: "tech", price: 44.99, tagline: "Setup de ensueño con un click que da gustito.", badge: "TRENDING", hue: 300, rating: 4.8, proof: "Favorito del mes" },
  { id: "maceta-levitante", name: "Maceta Levitante Flotante", category: "tech", price: 49.99, tagline: "Una planta que flota y gira sobre su base magnética.", badge: "EDICIÓN LIMITADA", hue: 275, rating: 4.7, proof: "Edición limitada" },

  // — Hogar Aesthetic —
  { id: "humidificador-llama", name: "Humidificador Llama Aurora", category: "hogar", price: 26.99, tagline: "Niebla con fuego de mentira. Ambiente cozy al instante.", badge: "VIRAL", hue: 18, rating: 4.7, proof: "Viral en TikTok", featured: true },
  { id: "difusor-volcan", name: "Difusor Niebla Volcán", category: "hogar", price: 22.99, tagline: "Erupción de vapor aromático. Hipnótico.", badge: "TRENDING", hue: 25, rating: 4.6, proof: "Tendencia 2026" },
  { id: "organizador-giratorio", name: "Organizador Maquillaje 360°", category: "hogar", price: 21.99, tagline: "Todo tu maquillaje en una torre que gira.", hue: 315, rating: 4.6, proof: "El más buscado" },
  { id: "espejo-hollywood", name: "Espejo Hollywood LED Táctil", category: "hogar", price: 38.99, compareAt: 59.99, tagline: "Luz de estrella para tu mejor ángulo.", badge: "TOP VENTAS", hue: 295, rating: 4.8, proof: "Top de la semana" },
  { id: "mantita-nube", name: "Mantita Nube Ultrasuave", category: "hogar", price: 27.99, tagline: "Como abrazar una nube. Adiós, frío.", hue: 322, rating: 4.9, proof: "Lo más guardado" },
  { id: "alfombra-margarita", name: "Alfombra Margarita Mullida", category: "hogar", price: 23.99, tagline: "El detalle cottage que tu cuarto pedía.", badge: "TRENDING", hue: 96, rating: 4.5, proof: "Tendencia 2026" },

  // — Self-care —
  { id: "gua-sha-set", name: "Set Gua Sha + Roller Cuarzo", category: "selfcare", price: 15.99, compareAt: 29.99, tagline: "Ritual facial de spa coreano en tu baño.", badge: "VIRAL", hue: 152, rating: 4.8, proof: "Viral en TikTok", featured: true },
  { id: "ice-roller", name: "Rodillo Hielo Facial Ice", category: "selfcare", price: 12.99, tagline: "Desinflama y despierta la cara en 60 segundos.", hue: 188, rating: 4.6, proof: "El más buscado" },
  { id: "mascara-led", name: "Mascarilla LED Skincare", category: "selfcare", price: 64.99, tagline: "Fototerapia de salón. El glow que se nota.", badge: "NUEVO", hue: 268, rating: 4.5, proof: "Recién llegado" },
  { id: "masajeador-cervical", name: "Masajeador Cervical Smart", category: "selfcare", price: 34.99, tagline: "Adiós tensión de cuello a golpe de impulsos.", hue: 205, rating: 4.5, proof: "Favorito del mes" },
  { id: "secador-ionico", name: "Secador Iónico Compacto", category: "selfcare", price: 29.99, tagline: "Pelo de peluquería, plegable para viajar.", badge: "TRENDING", hue: 318, rating: 4.6, proof: "Tendencia 2026" },
  { id: "kit-manicura-gel", name: "Kit Manicura Gel UV", category: "selfcare", price: 32.99, tagline: "Uñas de salón en casa por una fracción del precio.", hue: 305, rating: 4.7, proof: "El más buscado" },

  // — Accesorios —
  { id: "tote-holografico", name: "Bolso Tote Holográfico", category: "accesorios", price: 24.99, tagline: "Cambia de color con la luz. El bolso que todas miran.", badge: "TRENDING", hue: 285, rating: 4.6, proof: "Tendencia 2026", featured: true },
  { id: "set-anillos-acero", name: "Set 6 Anillos Acero Inox", category: "accesorios", price: 13.99, compareAt: 24.99, tagline: "No se oxidan, no manchan. Stack perfecto.", badge: "TOP VENTAS", hue: 230, rating: 4.8, proof: "Top de la semana" },
  { id: "collar-mariposa", name: "Collar Mariposa Cristal", category: "accesorios", price: 16.99, tagline: "La mariposa que brilla distinto en cada foto.", badge: "VIRAL", hue: 300, rating: 4.7, proof: "Viral en TikTok" },
  { id: "gafas-y2k", name: "Gafas Y2K Futuristas", category: "accesorios", price: 17.99, tagline: "Energía 2000 para tu próximo fit.", badge: "TRENDING", hue: 255, rating: 4.4, proof: "Tendencia 2026" },
  { id: "rinonera-cyber", name: "Riñonera Crossbody Cyber", category: "accesorios", price: 21.99, tagline: "Manos libres con actitud. Reflectante de noche.", badge: "NUEVO", hue: 198, rating: 4.5, proof: "Recién llegado" },
  { id: "beanie-aesthetic", name: "Gorro Beanie Aesthetic", category: "accesorios", price: 14.99, tagline: "El gorro que combina con absolutamente todo.", hue: 275, rating: 4.6, proof: "Favorito del mes" },

  // — Catálogo ampliado · Tanda 1 (Alibaba) —
  { id: "soporte-monitor-cajon-hub", name: "Soporte Monitor con Cajón y Hub USB", category: "tech", price: 34.99, badge: "VIRAL", hue: 210, rating: 4.7, proof: "Viral en TikTok", tagline: "Eleva tu pantalla y ordena el caos de cables en un solo gesto.", seo: "Elevador de monitor con hub USB y cajón organizador para escritorio gaming aesthetic: ordena cables y eleva la pantalla. Ideal para setup minimalista, estudio y streaming." },
  { id: "alfombrilla-xxl-escritorio-pastel", name: "Alfombrilla XXL Escritorio Pastel", category: "tech", price: 17.99, badge: "TRENDING", hue: 300, rating: 4.6, proof: "Tendencia 2026", tagline: "El lienzo pastel que convierte tu mesa en un setup de revista.", seo: "Alfombrilla de escritorio XXL gaming en tonos pastel: base aesthetic para teclado y ratón, antideslizante y lavable. Personalizable con tu marca." },
  { id: "soporte-auriculares-rgb-hub", name: "Soporte Auriculares RGB con Hub USB", category: "tech", price: 27.99, hue: 195, rating: 4.5, proof: "Recién llegado", tagline: "Cuelga tus cascos con glow RGB y libera tu escritorio.", seo: "Soporte para cascos gaming con luz RGB y hub USB: libera espacio y da glow a tu setup. Perfecto para gamers, streamers y desk aesthetic." },
  { id: "reposamunecas-teclado-raton-gel", name: "Reposamuñecas Teclado/Ratón Gel Pastel", category: "tech", price: 16.99, hue: 320, rating: 4.6, proof: "El más buscado", tagline: "Comodidad pastel para horas de juego sin castigar tus muñecas.", seo: "Set reposamuñecas de gel para teclado y ratón en colores pastel: comodidad ergonómica para largas sesiones de gaming, estudio o teletrabajo." },
  { id: "bandeja-bajo-escritorio-cables", name: "Bandeja Bajo-Escritorio para Cables", category: "tech", price: 18.99, hue: 220, rating: 4.5, proof: "Lo más guardado", tagline: "Esconde regletas y cables: el antes/después que para el scroll.", seo: "Bandeja de gestión de cables bajo escritorio: oculta regletas y cables para un setup limpio y aesthetic. Montaje sin taladrar." },
  { id: "cojin-lumbar-reposapies", name: "Cojín Lumbar + Reposapiés Ergonómico", category: "hogar", price: 32.99, hue: 200, rating: 4.6, proof: "Favorito del mes", tagline: "Tu glow up de postura para gaming, estudio y home office.", seo: "Kit cojín lumbar y reposapiés ergonómico para silla de escritorio: mejora la postura en gaming, estudio y home office. Espuma viscoelástica y funda lavable." },
  { id: "lampara-escritorio-plegable", name: "Lámpara de Escritorio Plegable 3 en 1", category: "iluminacion", price: 36.99, badge: "NUEVO", hue: 215, rating: 4.7, proof: "Recién llegado", tagline: "Luz de estudio, reloj y carga inalámbrica: 3 en 1 que cabe en cualquier mesa.", seo: "Flexo LED plegable con reloj, carga inalámbrica y regulador táctil: luz de estudio aesthetic 3 en 1 para tu desk setup. Multifunción y ahorro de espacio." },
  { id: "kit-luz-ambiental-coche-rgb", name: "Kit Luz Ambiental Coche RGB con App", category: "iluminacion", price: 32.99, badge: "VIRAL", hue: 280, rating: 4.6, proof: "Viral en TikTok", tagline: "Convierte tu coche en modo aesthetic que cambia al ritmo de la música.", seo: "Kit de luz ambiental para coche RGB con control por app y música: transforma el interior en modo aesthetic con fibra óptica. Instalación adhesiva sin herramientas." },
  { id: "techo-estrellado-coche-led", name: "Techo Estrellado Coche LED", category: "iluminacion", price: 26.99, badge: "TRENDING", hue: 248, rating: 4.7, proof: "Tendencia 2026", tagline: "Un cielo de estrellas en tu techo para los viajes nocturnos.", seo: "Luz de techo estrellado para coche LED USB: convierte el techo en un cielo de estrellas para viajes nocturnos aesthetic. Efecto galaxia portátil y fácil de pegar." },
  { id: "tapacubos-led-flotantes", name: "Tapacubos LED Flotantes (set 4)", category: "accesorios", price: 39.99, badge: "EDICIÓN LIMITADA", hue: 255, rating: 4.5, proof: "Edición limitada", tagline: "El logo que nunca gira: magia visual para tus llantas.", seo: "Set de 4 tapacubos LED flotantes que se mantienen rectos en movimiento: dan un look premium y aesthetic a las llantas. Carga magnética e impermeables." },
  { id: "difusor-aromas-coche", name: "Difusor de Aromas Coche Aesthetic", category: "hogar", price: 12.99, hue: 25, rating: 4.5, proof: "El más buscado", tagline: "El detalle mono que perfuma tu coche con estilo.", seo: "Difusor de aromas para coche con clip de rejilla y diseño aesthetic: ambienta tu coche con estilo y recargas tú el perfume. Detalle mono que combina con tu deco." },
  { id: "set-accesorios-coche-aesthetic", name: "Set Accesorios Coche Aesthetic", category: "accesorios", price: 24.99, badge: "TRENDING", hue: 300, rating: 4.6, proof: "Tendencia 2026", tagline: "El girly car setup que arrasa en TikTok, en un solo pack.", seo: "Set de accesorios de coche aesthetic: fundas de cinturón, colgante y detalles cute para personalizar tu coche con vibe TikTok. Pack regalo con tu marca." },
  { id: "set-collar-bandana-lazo", name: "Set Collar + Bandana + Lazo a Juego", category: "accesorios", price: 18.99, hue: 290, rating: 4.6, proof: "Favorito del mes", tagline: "Looks coordinados pet & me para las fotos más adorables.", seo: "Set collar, bandana y lazo a juego para perro o gato en tonos pastel: looks coordinados pet & me para fotos aesthetic. Ajustable, suave y resistente." },
  { id: "cama-sofa-mini-mascota", name: "Cama Sofá Mini para Mascota", category: "hogar", price: 49.99, badge: "TOP VENTAS", hue: 322, rating: 4.8, proof: "Top de la semana", tagline: "El mini sofá que parece mueble humano y enamora a tu mascota.", seo: "Cama-sofá mini para gato o perro con estilo de mueble real: deco de habitación que es también cama cómoda para tu mascota. Tendencia pet furniture aesthetic." },
  { id: "alfombrilla-refrescante-gel-mascotas", name: "Alfombrilla Refrescante de Gel para Mascotas", category: "hogar", price: 24.99, hue: 188, rating: 4.5, proof: "Recién llegado", tagline: "Alivia el calor del verano sin electricidad ni agua.", seo: "Alfombrilla refrescante de gel para perros y gatos: alivia el calor del verano sin electricidad ni agua, se autorrecarga. Lavable y antideslizante." },
  { id: "comedero-antiatragantamiento", name: "Comedero Antiatragantamiento Slow Feeder", category: "hogar", price: 15.99, hue: 152, rating: 4.6, proof: "Lo más guardado", tagline: "Ralentiza la comida y cuida la digestión de tu peludo.", seo: "Comedero antiatragantamiento (slow feeder) para perros y gatos: ralentiza la comida, mejora la digestión y reduce el estrés. Diseño laberinto y colores pastel." },
  { id: "cepillo-deshedding", name: "Cepillo Quita-Pelo Deshedding Pro", category: "hogar", price: 16.99, badge: "VIRAL", hue: 205, rating: 4.7, proof: "Viral en TikTok", tagline: "Adiós a la muda: resultados satisfying al instante.", seo: "Cepillo deshedding profesional para perros y gatos: elimina el pelo muerto y reduce la muda con un botón de auto-limpieza. Resultados visibles al instante." },
  { id: "botella-agua-portatil-mascota", name: "Botella de Agua Portátil 2 en 1 para Paseo", category: "accesorios", price: 18.99, hue: 195, rating: 4.6, proof: "El más buscado", tagline: "Bebedero de paseo sin goteo: imprescindible para salidas.", seo: "Botella de agua portátil 2 en 1 para perros: bebedero de paseo con dispensador de un toque, sin goteo. Imprescindible aesthetic para salidas y viajes." },
  { id: "fuente-agua-silenciosa-gatos", name: "Fuente de Agua Silenciosa para Gatos", category: "hogar", price: 34.99, badge: "NUEVO", hue: 190, rating: 4.6, proof: "Recién llegado", tagline: "Agua fresca en circulación que anima a tu gato a beber más.", seo: "Fuente de agua silenciosa para gatos con luz LED y filtro: agua fresca en circulación que anima a tu gato a beber más. Diseño minimalista aesthetic." },
  { id: "spray-dispensador-aceite", name: "Spray Dispensador de Aceite 2 en 1", category: "hogar", price: 15.99, badge: "VIRAL", hue: 96, rating: 4.7, proof: "Viral en TikTok", tagline: "El gadget #1 de la freidora de aire: rocía el aceite justo.", seo: "Spray dispensador de aceite 2 en 1 de cristal: rocía o vierte el aceite justo para freidora de aire, ensaladas y plancha. Cocina más sana y aesthetic." },
  { id: "cubo-basura-sensor", name: "Cubo de Basura Cocina con Sensor", category: "hogar", price: 59.99, hue: 215, rating: 4.6, proof: "Favorito del mes", tagline: "La tapa que se abre sola: tu cocina en modo futurista.", seo: "Cubo de basura inteligente con sensor sin contacto para cocina: se abre solo al acercar la mano, higiénico y aesthetic. Acero mate y cierre suave." },
  { id: "hervidor-huevos-electrico", name: "Hervidor Rápido de Huevos Eléctrico", category: "hogar", price: 27.99, hue: 45, rating: 4.5, proof: "El más buscado", tagline: "Huevos perfectos en minutos y apagado automático.", seo: "Hervidor rápido de huevos eléctrico para 7 unidades: huevos perfectos (duros, mollet, pochados) en minutos con apagado automático. Compacto y aesthetic." },
  { id: "cortador-uvas-tomates", name: "Cortador de Uvas y Tomates Cherry", category: "hogar", price: 11.99, hue: 340, rating: 4.5, proof: "Lo más guardado", tagline: "Parte 20 uvas de una pasada: snack prep satisfying y seguro.", seo: "Cortador rápido de uvas y tomates cherry: parte en mitades en un gesto, ideal para meriendas infantiles y bowls aesthetic. Seguro y fácil de limpiar." },
  { id: "maquina-helado-enrollado", name: "Máquina de Helado Enrollado Casero", category: "hogar", price: 64.99, badge: "EDICIÓN LIMITADA", hue: 320, rating: 4.6, proof: "Edición limitada", tagline: "Haz los ice cream rolls virales de street food en tu cocina.", seo: "Máquina de helado enrollado casero con placa fría: crea ice cream rolls como en los vídeos virales de street food. Postres aesthetic y diversión en familia." },

  // — Catálogo ampliado · Tanda 2 (Alibaba) —
  { id: "set-moldes-hielo", name: "Set Moldes Cubitos Hielo XXL y Esfera", category: "hogar", price: 13.99, hue: 200, rating: 4.6, proof: "Lo más guardado", tagline: "Hielo esfera aesthetic que no agua tus cafés ni tus cócteles.", seo: "Set de moldes de silicona para cubitos de hielo gigantes y esferas: hielo aesthetic que no agua tus bebidas, ideal para cafés y cócteles de verano." },
  { id: "mini-wafflera-pastel", name: "Mini Wafflera Antiadherente Pastel", category: "hogar", price: 26.99, hue: 330, rating: 4.6, proof: "Favorito del mes", tagline: "Gofres y tortitas monos en 5 minutos para tu brunch de feed.", seo: "Mini wafflera antiadherente en color pastel: gofres y tortitas monas en 5 minutos para desayunos aesthetic. Compacta, fácil de limpiar y mona en la encimera." },
  { id: "tabla-pilates-bandas", name: "Tabla de Pilates Portátil con Bandas", category: "selfcare", price: 54.99, badge: "TOP VENTAS", hue: 330, rating: 4.7, proof: "Top de la semana", tagline: "El Pilates board que petó el FitTok: entrena en casa modo that girl.", seo: "Tabla de Pilates portátil con bandas de resistencia: entrena todo el cuerpo en casa con la rutina viral that girl. Plegable, completa y aesthetic." },
  { id: "esterilla-yoga-plegable", name: "Esterilla Yoga Plegable de Viaje", category: "selfcare", price: 32.99, badge: "TRENDING", hue: 320, rating: 4.6, proof: "Tendencia 2026", tagline: "La esterilla doble cara que cabe en el bolso para entrenar donde sea.", seo: "Esterilla de yoga plegable de viaje doble cara: antideslizante, ligera y compacta para entrenar en cualquier sitio. Colores pastel para tu rutina aesthetic." },
  { id: "set-bandas-resistencia", name: "Set Mini Bandas Resistencia Pastel", category: "selfcare", price: 16.99, hue: 152, rating: 4.6, proof: "El más buscado", tagline: "Tonifica glúteos y piernas en casa con el set pastel del FitTok.", seo: "Set de mini bandas de resistencia de tela en tonos pastel: tonifica glúteos y piernas en casa, antideslizantes. Incluye bolsa, listas para tu that girl routine." },
  { id: "mini-stepper-plegable", name: "Mini Stepper Plegable con Display", category: "selfcare", price: 64.99, badge: "NUEVO", hue: 205, rating: 4.5, proof: "Recién llegado", tagline: "Cardio que cabe bajo el escritorio mientras ves tus series.", seo: "Mini stepper plegable con monitor de pasos y calorías: cardio que ahorra espacio para entrenar mientras ves series. Silencioso y aesthetic." },
  { id: "set-mancuernas-pastel", name: "Set Mancuernas Aesthetic Pastel", category: "selfcare", price: 29.99, hue: 300, rating: 4.5, proof: "Favorito del mes", tagline: "Las pesas pastel que decoran tu cuarto y tonifican a la vez.", seo: "Set de mancuernas de neopreno en colores pastel: pesas monas y antideslizantes para rutinas de tonificación en casa. Deco fitness aesthetic en tu cuarto." },
  { id: "botella-gym-2l", name: "Botella Gym 2L con Marcador Horario", category: "selfcare", price: 22.99, badge: "TRENDING", hue: 200, rating: 4.6, proof: "Tendencia 2026", tagline: "El reto de hidratación diario en la botella XL de moda en el gym.", seo: "Botella de gimnasio 2L con marcador de horas y funda con asa: reto de hidratación diario para tu rutina that girl. A prueba de fugas y aesthetic." },
  { id: "rodillo-masaje-recovery", name: "Rodillo Masaje Muscular y Pelota", category: "selfcare", price: 26.99, hue: 188, rating: 4.6, proof: "Lo más guardado", tagline: "El foam rolling satisfying que alivia agujetas post-entreno.", seo: "Set de rodillo de espuma y pelota de masaje para recuperación muscular: libera tensión post-entreno tipo foam rolling viral. Pastel y aesthetic." },
  { id: "set-organizadores-maleta", name: "Set Organizadores Maleta Compresión", category: "accesorios", price: 27.99, badge: "TRENDING", hue: 45, rating: 4.7, proof: "Tendencia 2026", tagline: "El set de cubes que ordena tu maleta como un puzzle perfecto.", seo: "Set de 6 organizadores de maleta con compresión: gana espacio y ordena la ropa por categorías para tu pack with me aesthetic. Tejido resistente y lavable." },
  { id: "neceser-colgante-viaje", name: "Neceser Colgante de Viaje", category: "accesorios", price: 24.99, hue: 290, rating: 4.6, proof: "El más buscado", tagline: "Se despliega como una tienda y se cuelga en el baño del hotel.", seo: "Neceser de viaje colgante con 4 compartimentos y gancho: organiza cosmética y skincare y cuélgalo en el baño del hotel. Aesthetic, impermeable y plegable." },
  { id: "almohada-cervical-viaje", name: "Almohada Cervical Viaje 2 en 1 con Capucha", category: "accesorios", price: 27.99, hue: 235, rating: 4.6, proof: "Favorito del mes", tagline: "La almohada-capucha mona para dormir en avión o tren.", seo: "Almohada cervical de viaje 2 en 1 con capucha: apoyo de cuello viscoelástico para dormir en avión o tren con total comodidad. Suave, lavable y aesthetic." },
  { id: "bascula-maleta-candado-tsa", name: "Báscula Digital de Maleta con Candado TSA", category: "accesorios", price: 18.99, hue: 210, rating: 4.5, proof: "Lo más guardado", tagline: "Pesa la maleta antes de volar y evita sobrecostes de equipaje.", seo: "Set báscula digital de equipaje y candado TSA: pesa la maleta antes de volar y evita sobrecostes, con cierre seguro. Compacto y aesthetic para viajeras." },
  { id: "funda-pasaporte-organizador", name: "Funda Pasaporte y Organizador de Documentos", category: "accesorios", price: 16.99, hue: 260, rating: 4.6, proof: "El más buscado", tagline: "La funda de pasaporte bonita con bloqueo RFID para tu travel haul.", seo: "Funda de pasaporte y organizador de documentos de viaje aesthetic: guarda tarjetas, billetes y pasaporte con bloqueo RFID. Detalle mono para tu travel haul." },
  { id: "adaptador-universal-viaje", name: "Adaptador Universal de Viaje con USB-C", category: "tech", price: 26.99, hue: 195, rating: 4.6, proof: "El más buscado", tagline: "Un solo gadget para enchufar en +150 países con carga rápida.", seo: "Adaptador universal de viaje con puertos USB-C y carga rápida: enchufa en +150 países en un solo gadget compacto. Imprescindible aesthetic para nómadas." },
  { id: "mega-pack-washi-tape", name: "Mega Pack Washi Tape Aesthetic", category: "accesorios", price: 19.99, badge: "TRENDING", hue: 315, rating: 4.7, proof: "Tendencia 2026", tagline: "Desplegar 30 rollos pastel es puro ASMR de papelería.", seo: "Mega pack de washi tape aesthetic (20-30 rollos): cintas decorativas para journaling, scrapbooking y bullet journal. Combo perfecto para tu stationery haul." },
  { id: "sticker-book-kawaii", name: "Sticker Book Coleccionable Kawaii", category: "accesorios", price: 18.99, hue: 300, rating: 4.6, proof: "Lo más guardado", tagline: "Cientos de stickers monos para decorar agenda, planner y journal.", seo: "Álbum de pegatinas kawaii con cientos de stickers aesthetic: decora agenda, planner y journal con detalles monos. El imprescindible del journaling viral." },
  { id: "set-boligrafos-gel-pastel", name: "Set Bolígrafos Gel Pastel y Marcadores", category: "accesorios", price: 16.99, hue: 290, rating: 4.6, proof: "El más buscado", tagline: "Apuntes monos con boli pastel que dan ganas de estudiar.", seo: "Set de bolígrafos de gel pastel y marcadores suaves: colores aesthetic para apuntes bonitos, journaling y bullet journal. Trazo fino y secado rápido." },
  { id: "cuaderno-discbound", name: "Cuaderno Discbound Personalizable", category: "accesorios", price: 24.99, hue: 280, rating: 4.6, proof: "Favorito del mes", tagline: "El planner aesthetic que personalizas y reordenas a tu gusto.", seo: "Cuaderno discbound personalizable de hojas reorganizables: planner aesthetic para estudio y productividad, con tapa de marca propia La TikiToki." },
  { id: "kit-junk-journal-vintage", name: "Kit Junk Journal Vintage", category: "accesorios", price: 22.99, hue: 38, rating: 4.5, proof: "Recién llegado", tagline: "Todo para empezar hoy tu álbum creativo vintage cozy.", seo: "Kit completo de junk journaling vintage: papeles, sellos, pegatinas y adornos para crear álbumes creativos aesthetic. Todo en uno para empezar hoy." },
  { id: "estuche-standing-pencil-case", name: "Estuche Grande Standing Pastel", category: "accesorios", price: 17.99, hue: 195, rating: 4.6, proof: "El más buscado", tagline: "El estuche que se levanta como un portalápices mono en tu mesa.", seo: "Estuche grande standing que se convierte en portalápices vertical: organiza tu material de estudio aesthetic en el escritorio. Gran capacidad y compacto." },
  { id: "pack-straps-movil-cuentas", name: "Pack Straps Móvil de Cuentas y Perlas", category: "accesorios", price: 15.99, badge: "VIRAL", hue: 300, rating: 4.7, proof: "Viral en TikTok", tagline: "El strap de cuentas que personaliza tu móvil y arrasa en TikTok.", seo: "Pack de straps de móvil de cuentas y perlas aesthetic: cuelga el teléfono al cuello o muñeca y personaliza tu look. Tendencia viral con +500k ventas al mes." },
  { id: "anillo-soporte-magsafe", name: "Anillo-Soporte MagSafe Plegable", category: "tech", price: 14.99, hue: 215, rating: 4.5, proof: "El más buscado", tagline: "Agarre y atril en un gesto: el grip que tu móvil necesita.", seo: "Anillo-soporte MagSafe plegable con grip loop: sujeta el móvil con un dedo y úsalo como atril para vídeos. Magnético, fino y aesthetic." },
  { id: "funda-movil-espejo-soporte", name: "Funda Móvil Aesthetic con Espejo y Soporte", category: "tech", price: 17.99, badge: "TRENDING", hue: 310, rating: 4.6, proof: "Tendencia 2026", tagline: "Protege, retoca tu look y ve vídeos sin manos con una sola funda.", seo: "Funda de móvil aesthetic con espejo y soporte integrado: protege, retoca tu look y ve vídeos sin manos. Diseños pastel personalizables con tu marca." },
  { id: "cartera-magsafe-crossbody", name: "Cartera Adhesiva MagSafe Crossbody 2 en 1", category: "accesorios", price: 19.99, hue: 25, rating: 4.5, proof: "Recién llegado", tagline: "Móvil y tarjetas al cuello: sal ligera y con las manos libres.", seo: "Cartera adhesiva MagSafe con correa crossbody 2 en 1: lleva tarjetas y el móvil al cuello, manos libres y aesthetic. Ideal para festivales y ciudad." },

  // — Catálogo ampliado · Tanda 3 (AliExpress) —
  { id: "barra-luz-monitor-rgb", name: "Barra de Luz Doble para Monitor RGB", category: "iluminacion", price: 32.99, badge: "VIRAL", hue: 280, rating: 4.7, proof: "Viral en TikTok", tagline: "Ilumina tu escritorio sin un solo reflejo en la pantalla.", seo: "Barra de luz LED para monitor con retroiluminación RGB: ilumina el escritorio sin reflejos en la pantalla, ideal para gaming setup y trabajo nocturno. Recargable, control táctil, envío a España." },
  { id: "soporte-auriculares-gamer-rgb", name: "Soporte Sujeta-Auriculares Gamer RGB", category: "tech", price: 27.99, hue: 200, rating: 4.6, proof: "Tendencia 2026", tagline: "La pieza central de tu desk tour, con RGB que late.", seo: "Soporte para cascos gaming con luz RGB y hub USB: organiza los auriculares y libera espacio en tu desk setup aesthetic. Base antideslizante, envío rápido a España." },
  { id: "reposamunecas-teclado-gel-pastel", name: "Reposamuñecas Teclado Gel Pastel", category: "tech", price: 17.99, hue: 320, rating: 4.6, proof: "El más buscado", tagline: "El detalle soft aesthetic que completa tu setup y cuida tus muñecas.", seo: "Reposamuñecas de gel suave para teclado y ratón: ergonomía cómoda en tonos pastel para tu setup aesthetic de estudio o gaming. Antideslizante, fácil de limpiar." },
  { id: "organizador-cables-clips-adhesivos", name: "Organizador Cables Escritorio Clips Adhesivos", category: "tech", price: 13.99, hue: 215, rating: 4.5, proof: "Lo más guardado", tagline: "Di adiós a los cables enredados y consigue una mesa impecable.", seo: "Organizador de cables con clips adhesivos para escritorio: di adiós a los cables enredados y consigue un setup minimalista y limpio. Fácil instalación sin herramientas." },
  { id: "soporte-elevador-monitor-cajon", name: "Soporte Elevador Monitor con Cajón", category: "hogar", price: 29.99, badge: "TRENDING", hue: 315, rating: 4.7, proof: "Tendencia 2026", tagline: "Eleva la pantalla a altura perfecta y esconde el caos en el cajón.", seo: "Soporte elevador para monitor con cajón organizador: eleva la pantalla a altura ergonómica y gana almacenaje en tu escritorio aesthetic. Madera/blanco minimalista." },
  { id: "funda-silicona-mando-grip", name: "Funda Silicona para Mando Grip Antideslizante", category: "accesorios", price: 12.99, hue: 290, rating: 4.5, proof: "El más buscado", tagline: "Personaliza tu mando en colores pastel con agarre extra cómodo.", seo: "Funda de silicona antideslizante para mando de consola: agarre cómodo, protección antiarañazos y colores aesthetic para personalizar tu setup gaming. Tacto suave." },
  { id: "consola-retro-portatil-400", name: "Mini Consola Retro Portátil 400 Juegos", category: "tech", price: 44.99, badge: "VIRAL", hue: 245, rating: 4.6, proof: "Viral en TikTok", tagline: "Nostalgia arcade de bolsillo con cientos de juegos clásicos.", seo: "Consola portátil retro con cientos de juegos clásicos: diversión arcade nostálgica de bolsillo, regalo perfecto gamer. Pantalla a color, batería recargable." },
  { id: "tira-led-coche-fibra-optica", name: "Tira LED Ambiental Coche Fibra Óptica RGB", category: "iluminacion", price: 32.99, badge: "TRENDING", hue: 270, rating: 4.7, proof: "Tendencia 2026", tagline: "El car glow up nº1: de coche básico a luxe en segundos.", seo: "Iluminación ambiental para coche con fibra óptica RGB y control por app: transforma el interior en un ambiente de lujo, sincroniza colores con la música. Instalación bajo salpicadero." },
  { id: "luz-led-coche-sonido", name: "Luz LED Coche Activada por Sonido", category: "iluminacion", price: 18.99, badge: "VIRAL", hue: 255, rating: 4.6, proof: "Viral en TikTok", tagline: "Luces que bailan al ritmo de tu música en cada viaje nocturno.", seo: "Luces LED para coche activadas por sonido: parpadean al ritmo de la música para noches de conducción con vibe aesthetic. USB, varios colores, fácil de pegar." },
  { id: "difusor-coche-rejilla-aesthetic", name: "Difusor de Aromas Coche Aesthetic Rejilla", category: "hogar", price: 13.99, hue: 25, rating: 4.5, proof: "El más buscado", tagline: "Tu coche siempre con olor fresco y un detalle mono en la rejilla.", seo: "Difusor de aromas para coche con clip de rejilla: tu coche siempre con olor fresco y un detalle decorativo mono. Recargable con aceites esenciales, diseño minimalista." },
  { id: "mini-cubo-basura-coche", name: "Cubo de Basura Mini para Coche con Tapa", category: "hogar", price: 14.99, hue: 320, rating: 4.5, proof: "Lo más guardado", tagline: "Interior limpio y sin olores: cabe en el portavasos.", seo: "Mini papelera para coche con tapa y cierre hermético: mantén el interior limpio y ordenado sin malos olores. Compacta, cabe en el portavasos, colores pastel." },
  { id: "soporte-movil-coche-magsafe", name: "Soporte Móvil Coche MagSafe Magnético", category: "tech", price: 19.99, badge: "TRENDING", hue: 210, rating: 4.6, proof: "Tendencia 2026", tagline: "El click magnético que fija tu móvil para el GPS manos libres.", seo: "Soporte de móvil para coche magnético compatible MagSafe: fija el teléfono con un click para GPS manos libres, agarre ultrafuerte. Rotación 360°, fácil instalación." },
  { id: "funda-volante-peludo-aesthetic", name: "Funda Volante Coche Peludo Aesthetic", category: "accesorios", price: 18.99, hue: 330, rating: 4.5, proof: "Favorito del mes", tagline: "El toque cozy y femenino que viste tu coche en tonos aesthetic.", seo: "Funda de volante peluda y suave en tonos aesthetic: agarre cómodo y un toque cozy y femenino para tu coche. Lavable, universal, antideslizante." },
  { id: "cepillo-quitapelos-mascota", name: "Cepillo Quita-Pelos Mascota Reutilizable", category: "hogar", price: 17.99, badge: "VIRAL", hue: 200, rating: 4.7, proof: "Viral en TikTok", tagline: "El deshedding satisfying que retira el pelo muerto al instante.", seo: "Cepillo deslanador para perros y gatos: retira el pelo muerto y reduce la caída hasta un 90%, masaje relajante para tu mascota. Botón de autolimpieza, mango ergonómico." },
  { id: "fuente-agua-automatica-mascotas", name: "Fuente de Agua Automática para Gatos y Perros", category: "hogar", price: 34.99, badge: "NUEVO", hue: 190, rating: 4.6, proof: "Recién llegado", tagline: "Agua fresca en movimiento que anima a tu mascota a hidratarse.", seo: "Fuente de agua automática para mascotas con filtro: agua fresca y en movimiento que anima a tu gato o perro a hidratarse. Silenciosa, LED, fácil de limpiar." },
  { id: "pelota-automatica-mascota", name: "Juguete Interactivo Pelota Automática Mascota", category: "hogar", price: 22.99, hue: 152, rating: 4.5, proof: "El más buscado", tagline: "Rueda y cambia de dirección sola para horas de juego.", seo: "Pelota interactiva automática para gatos y perros: rueda y cambia de dirección sola para horas de juego mientras no estás. Recargable USB, modo inteligente." },
  { id: "alfombrilla-gel-mascota-verano", name: "Alfombrilla Refrescante Gel Mascota Verano", category: "hogar", price: 23.99, hue: 188, rating: 4.5, proof: "Lo más guardado", tagline: "Alivia el calor del verano sin electricidad ni agua.", seo: "Alfombrilla refrescante de gel para mascotas: alivia el calor del verano y mantiene fresco a tu perro o gato sin electricidad. Autoenfriable, lavable, no tóxica." },
  { id: "comedero-lento-laberinto", name: "Comedero Lento Antiansiedad Aesthetic", category: "hogar", price: 16.99, hue: 96, rating: 4.6, proof: "Favorito del mes", tagline: "Ralentiza la comida, mejora la digestión y entretiene a tu peludo.", seo: "Comedero lento con laberinto para perros y gatos: ralentiza la comida, mejora la digestión y entretiene. Silicona antideslizante, colores aesthetic, apto lavavajillas." },
  { id: "cortador-verduras-12en1", name: "Cortador de Verduras Multifunción 12 en 1", category: "hogar", price: 24.99, badge: "TOP VENTAS", hue: 110, rating: 4.6, proof: "Top de la semana", tagline: "Pica, ralla y corta en segundos: el cooking hack que hipnotiza.", seo: "Cortador de verduras multifunción 12 en 1: pica, ralla y corta en segundos para cocinar más rápido y sano. Cuchillas de acero, recoge-restos integrado, fácil de limpiar." },
  { id: "selladora-bolsas-termica-usb", name: "Selladora de Bolsas Térmica Portátil USB", category: "hogar", price: 13.99, hue: 200, rating: 4.5, proof: "Lo más guardado", tagline: "Cierra al vacío snacks y alimentos: meal prep siempre fresco.", seo: "Mini selladora de bolsas térmica recargable USB: cierra al vacío snacks y alimentos para mantenerlos frescos, ideal meal prep. De bolsillo, con imán de nevera." },
  { id: "espumador-leche-electrico", name: "Espumador de Leche Eléctrico Inalámbrico", category: "hogar", price: 16.99, hue: 30, rating: 4.6, proof: "El más buscado", tagline: "Café con espuma cremosa, matcha o proteína como en cafetería.", seo: "Espumador de leche eléctrico recargable: prepara café con espuma cremosa, matcha o proteína como en cafetería desde casa. De mano, acero inoxidable." },
  { id: "bascula-cocina-digital", name: "Báscula de Cocina Digital Minimalista", category: "hogar", price: 18.99, hue: 210, rating: 4.6, proof: "Favorito del mes", tagline: "Pesa al gramo para recetas perfectas y batch cooking clean.", seo: "Báscula de cocina digital de precisión con diseño minimalista: pesa ingredientes al gramo para recetas perfectas y batch cooking. Pantalla LED, recargable, fina." },
  { id: "molde-helados-cubitos-aesthetic", name: "Molde Helados Caseros y Cubitos Forma Aesthetic", category: "hogar", price: 12.99, hue: 320, rating: 4.5, proof: "Lo más guardado", tagline: "Bebidas y postres monos con cubitos de corazón y esfera.", seo: "Moldes de silicona para hielo y helados con formas aesthetic (corazón, esfera): bebidas y postres monos para tus vídeos de cocina. Sin BPA, flexibles, reutilizables." },
  { id: "dispensador-cereal-hermetico", name: "Dispensador de Cereal y Snacks Hermético", category: "hogar", price: 21.99, hue: 45, rating: 4.6, proof: "El más buscado", tagline: "Despensa estilo Pinterest con alimentos siempre frescos.", seo: "Dispensador hermético para cereales y snacks: despensa ordenada estilo Pinterest y alimentos siempre frescos. Apilable, etiqueta incluida, fácil de servir." },
  { id: "comba-inteligente-sin-cuerda", name: "Cuerda de Saltar Inteligente Sin Cuerda con Contador", category: "selfcare", price: 19.99, badge: "TRENDING", hue: 175, rating: 4.5, proof: "Tendencia 2026", tagline: "Cuenta saltos y calorías para entrenar en casa sin espacio.", seo: "Comba inteligente 2 en 1 con y sin cuerda y contador digital: cuenta saltos y calorías para entrenar en casa sin espacio. Recargable, pesas extraíbles." },

  // — Catálogo ampliado · Tanda 4 (AliExpress) —
  { id: "rueda-abdominal-retorno", name: "Rueda Abdominal con Retorno Automático", category: "selfcare", price: 24.99, badge: "TRENDING", hue: 175, rating: 4.6, proof: "Tendencia 2026", tagline: "Trabaja el core con retorno asistido: progresivo, seguro y muy demostrable.", seo: "Rueda abdominal con sistema de retorno automático: trabaja el core de forma segura y progresiva en casa. Antideslizante, plegable, con rodillera incluida." },
  { id: "mini-pistola-masaje-muscular", name: "Mini Masajeador Muscular Pistola Portátil", category: "selfcare", price: 39.99, badge: "VIRAL", hue: 188, rating: 4.7, proof: "Viral en TikTok", tagline: "Alivia tensión y acelera la recuperación post-entreno, de bolsillo.", seo: "Mini pistola de masaje muscular recargable: alivia tensión y acelera la recuperación tras entrenar, de bolsillo. Varios cabezales y niveles de potencia, silenciosa." },
  { id: "gomas-resistencia-tela-gluteos", name: "Gomas Resistencia Fitness Set Tela", category: "selfcare", price: 16.99, hue: 152, rating: 4.6, proof: "El más buscado", tagline: "El pack base del FitTok para tonificar glúteos y piernas en casa.", seo: "Set de bandas de resistencia de tela antideslizantes: entrena glúteos y piernas en casa o gym con distintos niveles. Lavables, con bolsa, no se enrollan." },
  { id: "botella-gym-2l-pajita", name: "Botella Agua Gym 2L con Marcador y Pajita", category: "selfcare", price: 18.99, hue: 200, rating: 4.6, proof: "Lo más guardado", tagline: "Cumple tu reto de hidratación diario con la botella XL del gym.", seo: "Botella de agua deportiva de 2L con marcador horario y pajita: cumple tu reto de hidratación diaria en el gym o la oficina. Sin BPA, asa, motivacional." },
  { id: "bolsa-gym-impermeable-aesthetic", name: "Bolsa Gym Impermeable Aesthetic", category: "accesorios", price: 32.99, badge: "TRENDING", hue: 290, rating: 4.6, proof: "Tendencia 2026", tagline: "Llévalo todo al gym con estilo y orden, hasta las zapatillas.", seo: "Bolsa de deporte impermeable con compartimento para zapatillas: lo llevas todo al gym con estilo y orden. Tonos aesthetic, ligera, correa ajustable." },
  { id: "organizador-cables-viaje-estuche", name: "Organizador de Cables de Viaje Estuche", category: "accesorios", price: 16.99, hue: 260, rating: 4.6, proof: "El más buscado", tagline: "Cables, power bank y auriculares siempre ordenados en la maleta.", seo: "Estuche organizador de cables y cargadores para viajes: cables, power bank y auriculares siempre ordenados en la maleta. Compacto, resistente al agua, bolsillos elásticos." },
  { id: "cubos-compresion-maleta-pack", name: "Set Cubos de Compresión para Maleta", category: "accesorios", price: 26.99, badge: "VIRAL", hue: 45, rating: 4.7, proof: "Viral en TikTok", tagline: "El packing hack que dobla el espacio: cierra la cremallera y comprime.", seo: "Set de organizadores de equipaje con compresión: dobla el espacio de la maleta y viaja con todo clasificado. Cremallera de compresión, varios tamaños, ligeros." },
  { id: "bascula-equipaje-portatil", name: "Báscula Digital de Equipaje Portátil", category: "accesorios", price: 14.99, hue: 210, rating: 4.5, proof: "Lo más guardado", tagline: "Pesa la maleta antes de volar y evita el sobrecoste del aeropuerto.", seo: "Báscula digital de equipaje de mano: pesa la maleta antes de volar y evita el sobrecoste del aeropuerto. Compacta, pantalla LCD, gancho resistente." },
  { id: "almohada-cervical-memory-foam", name: "Almohada Cervical de Viaje Memory Foam", category: "accesorios", price: 22.99, hue: 235, rating: 4.6, proof: "El más buscado", tagline: "Soporte cómodo de memory foam para dormir en avión, tren o coche.", seo: "Almohada cervical de viaje de memory foam: soporte cómodo para el cuello en avión, tren o coche, duerme sin dolores. Funda lavable, clip para mochila, plegable." },
  { id: "adaptador-universal-viaje-usbc", name: "Adaptador Universal de Viaje USB-C", category: "tech", price: 24.99, hue: 195, rating: 4.6, proof: "El más buscado", tagline: "Carga todos tus dispositivos en +150 países desde un solo enchufe.", seo: "Adaptador universal de viaje con puertos USB-C y USB: carga todos tus dispositivos en más de 150 países desde un solo enchufe. Compacto, con fusible de seguridad." },
  { id: "boligrafos-gel-pastel-coreano", name: "Set Bolígrafos Gel Pastel Estética Coreana", category: "accesorios", price: 15.99, badge: "TRENDING", hue: 300, rating: 4.6, proof: "Tendencia 2026", tagline: "Colores monos estilo coreano para journaling y apuntes bonitos.", seo: "Set de bolígrafos de gel en tonos pastel estilo coreano: escritura suave y colores monos para journaling, apuntes y bullet journal. Punta fina, secado rápido." },
  { id: "notas-adhesivas-marcadores-aesthetic", name: "Set Notas Adhesivas y Marcadores Aesthetic", category: "accesorios", price: 12.99, hue: 315, rating: 4.5, proof: "Lo más guardado", tagline: "Organiza apuntes y agenda con un toque kawaii y productivo.", seo: "Pack de notas adhesivas y marcadores con formas aesthetic: organiza apuntes y agenda con un toque kawaii y productivo. Reposicionables, variadas, ideal estudio." },
  { id: "estuche-standing-lapices-pie", name: "Estuche Organizador Standing de Lápices", category: "accesorios", price: 18.99, hue: 285, rating: 4.6, proof: "Favorito del mes", tagline: "El estuche que se despliega de pie y monta tu rincón de estudio.", seo: "Estuche que se transforma en organizador vertical de pie: lleva el material y monta tu rincón de estudio al instante. Compartimentos, tela resistente, aesthetic." },
  { id: "set-sellos-journaling-diy", name: "Set Sellos Personalizados DIY Journaling", category: "accesorios", price: 14.99, hue: 38, rating: 4.5, proof: "Recién llegado", tagline: "Estampa detalles únicos en tu bullet journal, cartas y packaging.", seo: "Set de sellos aesthetic para journaling y scrapbooking: decora tu bullet journal, cartas y packaging con detalles únicos. Tinta incluida, motivos variados." },
  { id: "planificador-magnetico-nevera", name: "Pizarra Calendario Magnético Nevera Aesthetic", category: "hogar", price: 17.99, hue: 320, rating: 4.5, proof: "El más buscado", tagline: "Organiza menús, tareas y metas con estilo en la cocina, borrable.", seo: "Planificador semanal magnético para nevera: organiza menús, tareas y metas con estilo en la cocina. Borrable, rotulador incluido, diseño minimalista." },
  { id: "grip-plegable-movil-magsafe", name: "Grip Plegable Móvil MagSafe Anillo Soporte", category: "tech", price: 15.99, badge: "TRENDING", hue: 215, rating: 4.6, proof: "Tendencia 2026", tagline: "Agarre seguro y soporte 2 en 1 que se despliega para ver vídeos.", seo: "Grip plegable para móvil compatible MagSafe: agarre seguro y soporte 2 en 1 para ver vídeos manos libres. Ultrafino, magnético, colores aesthetic." },
  { id: "cartera-magsafe-tarjetero-iphone", name: "Cartera Magnética MagSafe Tarjetero iPhone", category: "accesorios", price: 18.99, hue: 25, rating: 4.5, proof: "Lo más guardado", tagline: "Lleva tus tarjetas pegadas al móvil, fino y con bloqueo RFID.", seo: "Tarjetero magnético compatible MagSafe para iPhone: lleva tus tarjetas pegadas al móvil, fino y con bloqueo RFID. Piel sintética, colores aesthetic, agarre fuerte." },
  { id: "soporte-tablet-movil-aluminio", name: "Soporte Tablet/Móvil Sobremesa Plegable Aluminio", category: "tech", price: 18.99, hue: 205, rating: 4.6, proof: "El más buscado", tagline: "Ángulo ajustable para estudiar, ver series o videollamadas cómoda.", seo: "Soporte plegable de aluminio para tablet y móvil: ángulo ajustable para estudiar, ver series o videollamadas cómodamente. Compacto, antideslizante, portátil." },
  { id: "funda-movil-espejo-cadena", name: "Funda Móvil con Espejo y Cadena Aesthetic", category: "accesorios", price: 16.99, badge: "VIRAL", hue: 305, rating: 4.6, proof: "Viral en TikTok", tagline: "Protege el móvil y conviértelo en bolso de mano con look Y2K.", seo: "Funda de móvil con espejo y cadena desmontable: protege el teléfono y lo conviertes en bolso de mano aesthetic. Antigolpes, espejo de retoque, look Y2K." },
  { id: "stylus-universal-tablet", name: "Lápiz Stylus Universal para Tablet", category: "tech", price: 24.99, hue: 210, rating: 4.5, proof: "Favorito del mes", tagline: "Escribe, dibuja y toma apuntes con precisión en tu tablet.", seo: "Lápiz stylus universal para tablet: escribe, dibuja y toma apuntes con precisión en tu tablet, alternativa accesible. Punta fina, recargable, rechazo de palma." },
  { id: "altavoz-bluetooth-mini-aesthetic", name: "Altavoz Bluetooth Mini Aesthetic", category: "tech", price: 21.99, hue: 290, rating: 4.6, proof: "Lo más guardado", tagline: "Sonido potente de bolsillo para tu cuarto, picnic o gym.", seo: "Altavoz Bluetooth mini con diseño aesthetic: sonido potente de bolsillo para tu cuarto, picnic o gym. Recargable, resistente a salpicaduras, colores pastel." },
  { id: "microfono-karaoke-led", name: "Micrófono Karaoke Inalámbrico con Luces LED", category: "tech", price: 32.99, badge: "TRENDING", hue: 260, rating: 4.6, proof: "Tendencia 2026", tagline: "Canta en casa con efectos de voz, luces LED y altavoz integrado.", seo: "Micrófono de karaoke inalámbrico Bluetooth con luces LED: canta en casa con efectos de voz y altavoz integrado, fiesta instantánea. Recargable, eco ajustable." },
  { id: "adaptador-jack-carga-2en1", name: "Adaptador Jack + Carga 2 en 1 Audio Split", category: "tech", price: 11.99, hue: 200, rating: 4.5, proof: "El más buscado", tagline: "Escucha con auriculares de cable mientras cargas, sin renunciar a nada.", seo: "Adaptador 2 en 1 para escuchar y cargar a la vez: usa auriculares con cable mientras cargas el móvil sin renunciar a nada. Compacto, compatible con varios modelos." },
  { id: "auriculares-diadema-gatito-led", name: "Auriculares Diadema Gaming Bluetooth Gatito", category: "tech", price: 32.99, badge: "VIRAL", hue: 305, rating: 4.6, proof: "Viral en TikTok", tagline: "Sonido inalámbrico y look kawaii con orejas de gato y LED.", seo: "Auriculares de diadema con orejas de gato y luces LED: sonido inalámbrico y look kawaii para gaming, streaming y música. Micrófono, cómodos, recargables." },
  { id: "lampara-luna-galaxia-levitante", name: "Lámpara Luna/Galaxia Levitante Magnética", category: "iluminacion", price: 54.99, badge: "EDICIÓN LIMITADA", hue: 280, rating: 4.7, proof: "Edición limitada", tagline: "Una esfera lunar que flota y gira sobre su base: scroll-stopper total.", seo: "Lámpara levitante magnética con esfera flotante iluminada: pieza de decoración futurista que flota y gira sobre su base. Luz cálida, regalo wow para escritorio." },

  // — Catálogo ampliado · Tanda 5 (Alibaba+AliExpress restantes) —
  { id: "soporte-movil-plegable-aluminio-mesa", name: "Soporte Móvil Plegable Aluminio de Mesa", category: "tech", price: 14.99, hue: 200, rating: 4.6, proof: "El más buscado", tagline: "El atril mono que sujeta tu móvil en la mesa para series y videollamadas.", seo: "Soporte de móvil plegable de aluminio para mesa en color pastel: atril ajustable para ver series, videollamadas y grabar. Compacto y aesthetic." },
  { id: "set-joyeria-acero-dorado-clean-girl", name: "Set Joyería Acero Dorado Clean Girl", category: "accesorios", price: 27.99, badge: "TRENDING", hue: 45, rating: 4.7, proof: "Tendencia 2026", tagline: "Collar, pulsera y pendientes dorados que no se oxidan: look clean girl en caja regalo.", seo: "Set de joyería de acero inoxidable dorado clean girl en caja regalo: collar, pulsera y pendientes que no se oxidan ni se ponen negros. Look minimal aesthetic." },
  { id: "bolso-tote-acolchado-puffer", name: "Bolso Tote Acolchado Puffer Aesthetic", category: "accesorios", price: 32.99, hue: 290, rating: 4.6, proof: "Favorito del mes", tagline: "El tote acolchado mono del momento: ligero, espacioso y para todo el día.", seo: "Bolso tote acolchado puffer aesthetic: ligero, espacioso y tendencia para el día a día, estudio o playa. Personalizable con tu marca La TikiToki." },
  { id: "bolso-media-luna-croissant", name: "Bolso Media Luna Croissant Tendencia", category: "accesorios", price: 29.99, badge: "VIRAL", hue: 35, rating: 4.7, proof: "Viral en TikTok", tagline: "El it-bag croissant que estiliza cualquier outfit y sale en todos los OOTD.", seo: "Bolso de hombro media luna (croissant) tendencia: forma it-bag que estiliza cualquier outfit aesthetic. Cuero vegano suave y colores neutros." },
  { id: "pack-bag-charms-peluche-cuentas", name: "Pack Bag Charms Peluche y Cuentas DIY", category: "accesorios", price: 17.99, hue: 305, rating: 4.6, proof: "El más buscado", tagline: "Decora tu bolso y mochila con colgantes monos: la tendencia bag charm.", seo: "Pack de bag charms de peluche y cuentas para personalizar bolsos: colgantes aesthetic tendencia bag charm para decorar tu bolso y mochila. Set variado DIY." },
  { id: "set-pulseras-cuarzo-piedras", name: "Set Pulseras Cuarzo y Piedras Naturales", category: "accesorios", price: 16.99, hue: 280, rating: 4.6, proof: "Lo más guardado", tagline: "Stack aesthetic con significado para apilar capas de piedras en la muñeca.", seo: "Set de pulseras de cuarzo y piedras naturales: stack aesthetic con significado para combinar capas en la muñeca. Tendencia wellness y mermaidcore 2026." },
  { id: "set-calentadores-pierna-coquette", name: "Set Calentadores de Pierna Coquette", category: "accesorios", price: 16.99, hue: 320, rating: 4.6, proof: "El más buscado", tagline: "Leg warmers suaves para outfits coquette con lazos: la megatendencia balletcore.", seo: "Set de calentadores de pierna coquette/balletcore: complemento suave para outfits aesthetic con lazos y volantes. Pack de colores pastel para combinar." },
  { id: "set-lazos-xl-saten-bow-stacking", name: "Set Lazos XL Satén Bow Stacking", category: "accesorios", price: 13.99, badge: "TRENDING", hue: 330, rating: 4.6, proof: "Tendencia 2026", tagline: "Apila lazos de satén en el pelo o el bolso: el peinado coquette viral.", seo: "Set de lazos XL de satén para bow stacking: lazos coquette para superponer en el pelo o bolso. Tendencia en búsquedas, look romántico aesthetic." },
  { id: "kit-rizos-sin-calor-heatless", name: "Kit Rizos Sin Calor Heatless Curls", category: "selfcare", price: 16.99, badge: "VIRAL", hue: 318, rating: 4.7, proof: "Viral en TikTok", tagline: "Te despiertas con ondas perfectas sin plancha y sin dañar el pelo.", seo: "Kit de rizos sin calor con varilla de satén y lazos: consigue ondas perfectas durmiendo, sin dañar el pelo. Dupe aesthetic del estilo Airwrap viral." },
  { id: "gafas-led-festival-difraccion", name: "Gafas LED Festival Difracción Recargables", category: "accesorios", price: 24.99, hue: 255, rating: 4.5, proof: "Tendencia 2026", tagline: "El accesorio rave que ilumina la fiesta con efecto difracción y modos de color.", seo: "Gafas LED de festival con efecto difracción y luces recargables: el accesorio rave que ilumina la fiesta con modos de color. Imprescindible aesthetic para festivales." },
  { id: "panel-pixel-led-programable", name: "Panel Pixel LED Programable por App", category: "iluminacion", price: 39.99, badge: "NUEVO", hue: 215, rating: 4.6, proof: "Recién llegado", tagline: "Escribe textos, relojes y animaciones en tu setup con estética retro-gamer.", seo: "Panel LED de píxeles programable por app: muestra texto, relojes, emojis y animaciones para personalizar tu setup. Recargable, miles de diseños, estética retro-gamer." },
  { id: "lampara-mesa-inalambrica-tactil-3-tonos", name: "Lámpara de Mesa Inalámbrica Táctil 3 Tonos", category: "iluminacion", price: 27.99, hue: 35, rating: 4.6, proof: "El más buscado", tagline: "Luz cálida sin cables que monta un rincón cozy de revista al instante.", seo: "Lámpara de mesa inalámbrica recargable con 3 temperaturas de luz: ambiente cozy sin cables para mesita, estantería o terraza. Táctil, regulable, diseño minimalista." },
  { id: "lampara-proyector-texto-pared", name: "Lámpara Proyector Texto y Logo a Pared", category: "iluminacion", price: 29.99, hue: 270, rating: 4.5, proof: "Recién llegado", tagline: "Proyecta tu frase favorita en la pared: deco personalizada y compartible.", seo: "Lámpara proyectora de imágenes y frases en la pared: crea un ambiente único con tu nombre o motivos aesthetic. Varias plantillas, ideal cuarto y eventos." },
  { id: "tira-neon-led-flexible-usb", name: "Tira Neón LED Flexible USB 5m", category: "iluminacion", price: 17.99, badge: "TRENDING", hue: 300, rating: 4.6, proof: "Tendencia 2026", tagline: "Dibuja formas y contornea tu cuarto con un brillo neón aesthetic.", seo: "Tira de neón LED flexible USB de 5m: dibuja formas y contornea tu cuarto o desk con un brillo neón aesthetic. Moldeable, varios colores, fácil de pegar." },
  { id: "caja-organizadora-mandos-tapa", name: "Caja Organizadora Mandos con Tapa Aesthetic", category: "hogar", price: 17.99, hue: 290, rating: 4.5, proof: "Lo más guardado", tagline: "Esconde el caos de mandos y cables en una caja cute y minimalista.", seo: "Caja organizadora con tapa para mandos, cables y trastos: salón y mesita ordenados con un diseño minimalista mono. Compartimentos, tela y fieltro, plegable." },
  { id: "organizador-joyas-viaje-estuche", name: "Organizador Joyas Viaje Compacto", category: "hogar", price: 18.99, hue: 285, rating: 4.6, proof: "El más buscado", tagline: "Anillos, collares y pendientes sin enredos ni pérdidas en la maleta.", seo: "Estuche organizador de joyas para viaje: anillos, collares y pendientes sin enredos ni pérdidas en la maleta. Compartimentos acolchados, cierre, compacto." },
  { id: "organizador-maquillaje-giratorio-360", name: "Organizador Maquillaje Giratorio 360° con Cajones", category: "hogar", price: 32.99, badge: "TOP VENTAS", hue: 315, rating: 4.6, proof: "Top de la semana", tagline: "El tocador de influencer que gira 360° con brochas, labiales y skincare a la vista.", seo: "Organizador de maquillaje giratorio 360° con cajones: tocador de influencer con brochas, labiales y skincare a la vista y ordenado. Transparente aesthetic, gran capacidad." },
  { id: "lampara-antimosquitos-led-aesthetic", name: "Lámpara LED Antimosquitos Aesthetic", category: "selfcare", price: 24.99, hue: 175, rating: 4.5, proof: "Recién llegado", tagline: "Noches tranquilas en verano sin químicos y con un diseño mono de mesita.", seo: "Lámpara antimosquitos LED USB silenciosa y sin químicos: noches tranquilas en verano con un diseño mono de mesita. Atrae y atrapa insectos, segura para niños y mascotas." },
  { id: "corrector-postura-ajustable", name: "Corrector de Postura Ajustable Discreto", category: "selfcare", price: 21.99, badge: "TRENDING", hue: 205, rating: 4.5, proof: "Tendencia 2026", tagline: "Alinea hombros y espalda durante el trabajo o el estudio para sentarte mejor.", seo: "Corrector de postura ajustable y discreto: alinea los hombros y la espalda durante el trabajo o el estudio para sentarte mejor. Transpirable, talla única, bajo la ropa." },
  { id: "mini-masajeador-cervical-portatil", name: "Mini Masajeador Cervical Eléctrico Portátil", category: "selfcare", price: 34.99, hue: 188, rating: 4.5, proof: "Favorito del mes", tagline: "Alivia la tensión del cuello tras horas de pantalla, con modos e intensidades.", seo: "Mini masajeador cervical eléctrico recargable: alivia la tensión del cuello y los hombros tras horas frente a la pantalla, modos e intensidades. Ligero, manos libres." },

  // — Catálogo ampliado · Tanda 6 (Shein) —
  { id: "top-corse-encaje-lace-up", name: "Top Corsé Encaje Lace-Up Going Out", category: "accesorios", price: 19.99, badge: "TRENDING", hue: 330, rating: 4.7, proof: "Tendencia 2026", tagline: "El going out top que para el scroll: corsé de encaje para tus noches.", seo: "Top corsé de encaje con cordones: la prenda viral para un look femenino y sexy de noche, perfecta para combinar con vaqueros baggy. Tallas desde la S, envío a España." },
  { id: "camiseta-mesh-manga-larga", name: "Camiseta Mesh Manga Larga Transparente", category: "accesorios", price: 16.99, hue: 285, rating: 4.6, proof: "El más buscado", tagline: "El básico de layering grunge que se pone debajo de todo.", seo: "Camiseta de malla mesh semitransparente de manga larga, básico de layering grunge y y2k para superponer sobre top o bikini. Estilo viral aesthetic." },
  { id: "falda-vaquera-maxi-denim", name: "Falda Vaquera Maxi Denim Largo", category: "accesorios", price: 26.99, badge: "TRENDING", hue: 210, rating: 4.7, proof: "Tendencia 2026", tagline: "El long denim maxi de 2026: cómoda, versátil y favorecedora.", seo: "Falda vaquera maxi larga, la pieza denim que sustituye al pantalón en 2026: cómoda, versátil y favorecedora. Estilo coastal y casual chic." },
  { id: "pantalon-cargo-parachute-baggy", name: "Pantalón Cargo Parachute Baggy", category: "accesorios", price: 27.99, hue: 95, rating: 4.6, proof: "Lo más guardado", tagline: "El cargo parachute con volumen que arrasa en el streetwear.", seo: "Pantalón cargo parachute baggy con bolsillos, esencial del streetwear y utility 2026 para un look cómodo y a la moda. Tallaje amplio, envío a España." },
  { id: "top-cami-encaje-coquette-lazo", name: "Top Cami Encaje Coquette con Lazo", category: "accesorios", price: 15.99, hue: 330, rating: 4.7, proof: "Favorito del mes", tagline: "El top soft girl con encaje y lazo que se hace haul una y otra vez.", seo: "Top de tirantes con encaje y lazo coquette: prenda romántica y femenina ideal para layering bajo cárdigan. Aesthetic balletcore viral. Tallas desde la S." },
  { id: "cardigan-corto-boton-perla", name: "Cárdigan Corto Botón Perla Balletcore", category: "accesorios", price: 23.99, hue: 300, rating: 4.6, proof: "El más buscado", tagline: "El crop cardigan de that girl: layering pulido y coqueto.", seo: "Cárdigan corto de punto con botones tipo perla, pieza balletcore y clean girl para un look pulido y coqueto sobre top de tirantes. Estilo viral 2026." },
  { id: "vestido-lencero-saten-slip", name: "Vestido Lencero Satén Slip Dress", category: "accesorios", price: 25.99, badge: "TRENDING", hue: 290, rating: 4.7, proof: "Tendencia 2026", tagline: "El slip dress old money que cae fluido de día a noche.", seo: "Vestido lencero de satén midi, prenda mob wife y coquette para un look elegante de día a noche. Cae fluido y favorece. Tallas desde la S, envío a España." },
  { id: "chaleco-punto-sweater-vest", name: "Chaleco de Punto Sin Mangas Sweater Vest", category: "accesorios", price: 19.99, hue: 38, rating: 4.5, proof: "Lo más guardado", tagline: "El preppy sweater vest que viste un look básico al instante.", seo: "Chaleco de punto sin mangas (sweater vest), básico preppy y academia para superponer sobre camisa. Estilo aesthetic vuelta al cole viral." },
  { id: "top-banera-strapless-tube", name: "Top Bañera Strapless Tube Top", category: "accesorios", price: 14.99, hue: 285, rating: 4.6, proof: "El más buscado", tagline: "El tube top básico que multiplica looks: 1 prenda, 5 outfits.", seo: "Top palabra de honor tipo tubo, prenda y2k imprescindible para combinar con cargos o falda. Aesthetic minimalista y sexy de salir. Tallas desde la S." },
  { id: "conjunto-punto-top-falda", name: "Conjunto Coordinado Punto Top + Falda", category: "accesorios", price: 32.99, badge: "TOP VENTAS", hue: 300, rating: 4.7, proof: "Top de la semana", tagline: "El matching set que resuelve un outfit completo en un clic.", seo: "Conjunto coordinado de punto (top + falda) a juego, el matching set que resuelve un outfit completo aesthetic en un clic. Estilo clean girl viral." },
  { id: "top-halter-espalda-descubierta", name: "Top Halter Espalda Descubierta Backless", category: "accesorios", price: 16.99, hue: 320, rating: 4.6, proof: "Lo más guardado", tagline: "El backless top con efecto sorpresa de espalda en cada giro.", seo: "Top halter de espalda descubierta, prenda sexy de noche para destacar la espalda en un look going out. Aesthetic y2k y elegante viral. Tallas desde la S." },
  { id: "vestido-babydoll-volantes", name: "Vestido Babydoll Volantes Coquette", category: "accesorios", price: 24.99, badge: "TRENDING", hue: 335, rating: 4.7, proof: "Tendencia 2026", tagline: "El babydoll princesa coquette que vuela en cámara.", seo: "Mini vestido babydoll con volantes y vuelo, prenda coquette y cottagecore súper femenina para primavera-verano. Estilo romántico viral. Tallas desde la S." },
  { id: "calentadores-brazo-arm-warmers", name: "Calentadores de Brazo de Punto Arm Warmers", category: "accesorios", price: 12.99, hue: 260, rating: 4.6, proof: "El más buscado", tagline: "El accesorio fairy grunge que completa el OOTD de frío.", seo: "Calentadores de brazo largos de punto (arm warmers), complemento grunge y coquette para estilizar un look de invierno aesthetic. Tendencia viral 2026." },
  { id: "baby-tee-print-grafico-y2k", name: "Camiseta Baby Tee Print Gráfico Y2K", category: "accesorios", price: 15.99, hue: 300, rating: 4.6, proof: "Lo más guardado", tagline: "La baby tee gráfica de los 2000: nostalgia y2k que arrasa.", seo: "Baby tee ajustada con print gráfico y2k, camiseta corta retro de los 2000 para un look nostálgico y juvenil. Aesthetic viral en TikTok. Tallas desde la S." },
  { id: "collar-choker-terciopelo", name: "Collar Gargantilla Choker Terciopelo", category: "accesorios", price: 10.99, hue: 280, rating: 4.6, proof: "El más buscado", tagline: "El choker noventero/y2k que viste cualquier escote con actitud.", seo: "Gargantilla choker de terciopelo, joya y2k y grunge para un look de noche con actitud. Complemento aesthetic viral que viste cualquier escote." },
  { id: "set-anillos-plata-piedra", name: "Set Anillos Plata Apilables con Piedra", category: "accesorios", price: 13.99, badge: "TRENDING", hue: 200, rating: 4.7, proof: "Tendencia 2026", tagline: "El ring stacking mermaidcore con piedras de colores que llena la mano.", seo: "Set de anillos de plata apilables con piedras de colores, mix de joyas para el ring stacking mermaidcore 2026. Look clean girl que no se oxida." },
  { id: "collar-charms-diy-personalizable", name: "Collar Charms DIY Personalizable", category: "accesorios", price: 16.99, badge: "VIRAL", hue: 290, rating: 4.6, proof: "Viral en TikTok", tagline: "El charm necklace DIY donde cada collar cuenta tu historia.", seo: "Collar de charms DIY personalizable con dijes variados, la joya viral del verano para crear un diseño único y contar tu historia. Aesthetic coquette." },
  { id: "pendientes-largos-cascada-statement", name: "Pendientes Largos Cascada Statement", category: "accesorios", price: 15.99, hue: 295, rating: 4.6, proof: "Lo más guardado", tagline: "El statement earring XL que para el scroll en eventos.", seo: "Pendientes largos de cascada statement, joya maximalista mob wife para elevar un look de fiesta o evento. Tendencia more is more viral 2026." },
  { id: "anillo-sello-chunky-signet", name: "Anillo Sello Chunky Signet Ring", category: "accesorios", price: 11.99, hue: 45, rating: 4.6, proof: "El más buscado", tagline: "El signet ring old money que viste la mano, unisex y atemporal.", seo: "Anillo de sello chunky dorado (signet ring), joya old money y unisex para un look pulido y atemporal. Tendencia aesthetic clean girl viral." },
  { id: "collar-inicial-letra-personalizada", name: "Collar Inicial Letra Personalizada", category: "accesorios", price: 13.99, badge: "TOP VENTAS", hue: 50, rating: 4.7, proof: "Top de la semana", tagline: "El collar de inicial: el regalo emocional nº1 para regalar.", seo: "Collar con inicial o letra personalizada, joya minimalista y regalo emocional para llevar tu inicial o la de alguien especial. Aesthetic clean girl viral." },
  { id: "set-pulseras-cuentas-friendship", name: "Set Pulseras Cuentas Charm Friendship", category: "accesorios", price: 14.99, hue: 300, rating: 4.6, proof: "El más buscado", tagline: "El bracelet stack de cuentas que llena la muñeca de verano.", seo: "Set de pulseras de cuentas con charms estilo friendship, stack colorido mermaidcore para apilar en la muñeca. Joyería de verano viral. Pack variado." },
  { id: "broche-lazo-perlas-coquette", name: "Broche Lazo Perlas Coquette Pin", category: "accesorios", price: 10.99, hue: 330, rating: 4.6, proof: "Lo más guardado", tagline: "El broche perla + lazo que viste chaqueta, bolso o pelo.", seo: "Broche de lazo con perlas coquette, detalle romántico para chaqueta, bolso o pelo. Los broches vuelven con fuerza en 2026 con vibe femenino." },
  { id: "pendientes-aro-corazon-estrella", name: "Pendientes Aro Corazón / Estrella", category: "accesorios", price: 11.99, hue: 320, rating: 4.6, proof: "Favorito del mes", tagline: "El cute hoop con dije: pendiente dopamina que petó en GRWM.", seo: "Pendientes de aro con corazón o estrella colgante, joya coquette y dopamine para un toque dulce y juguetón. Aesthetic viral que combina con todo." },
  { id: "set-joyas-strass-novia-evento", name: "Set Joyas Strass Conjunto Novia / Evento", category: "accesorios", price: 17.99, badge: "TRENDING", hue: 290, rating: 4.7, proof: "Tendencia 2026", tagline: "El conjunto glam que resuelve la joya de la noche en un carrito.", seo: "Conjunto de joyas con strass (collar + pendientes) para evento, boda o graduación, look glam coordinado de un solo carrito. Aesthetic statement viral." },
  { id: "charm-bolso-peluche-monstruo", name: "Charm de Bolso Peluche Monstruo", category: "accesorios", price: 14.99, badge: "VIRAL", hue: 305, rating: 4.7, proof: "Viral en TikTok", tagline: "El bag charm peluche colgante que petó en todos los OOTD.", seo: "Charm de bolso de peluche tipo monstruo coleccionable, el accesorio bag charm más viral de 2026 para personalizar cualquier bolso. Aesthetic juguetón." },

  // — Catálogo ampliado · Tanda 7 (Shein) —
  { id: "charm-bolso-lazo-saten", name: "Charm de Bolso Lazo Satén Grande", category: "accesorios", price: 12.99, badge: "NUEVO", hue: 330, rating: 4.6, proof: "Recién llegado", tagline: "El lazo gigante de satén que transforma un bolso básico al instante.", seo: "Charm de bolso con lazo de satén grande, detalle coquette para vestir el bolso con un toque femenino y romántico. Tendencia bag charm viral 2026." },
  { id: "bolso-hobo-slouchy-oversize", name: "Bolso Hobo Slouchy Cuero PU Oversize", category: "accesorios", price: 29.99, badge: "TRENDING", hue: 30, rating: 4.7, proof: "Tendencia 2026", tagline: "El big slouchy bag mob wife que lo lleva todo con vibe off-duty model.", seo: "Bolso hobo slouchy oversize de cuero PU, el it-bag amplio y desestructurado de 2026 para llevarlo todo con estilo mob wife. Aesthetic viral." },
  { id: "bolso-baguette-y2k-print", name: "Bolso Baguette Y2K con Print", category: "accesorios", price: 23.99, hue: 290, rating: 4.6, proof: "Lo más guardado", tagline: "El baguette de los 2000 para un what's in my bag con nostalgia y2k.", seo: "Bolso baguette de hombro estilo y2k con print, el bolso de los 2000 que vuelve para un look nostálgico de hombro. Aesthetic retro viral. Combinable." },
  { id: "gafas-sol-wraparound-shield", name: "Gafas de Sol Wraparound Shield Y2K", category: "accesorios", price: 15.99, hue: 250, rating: 4.6, proof: "El más buscado", tagline: "Las gafas shield futuristas que cambian toda la foto con actitud.", seo: "Gafas de sol wraparound tipo shield envolventes, el modelo statement futurista y2k para un outfit check con actitud. Aesthetic viral de verano." },
  { id: "gafas-sol-cat-eye-retro", name: "Gafas de Sol Cat-Eye Retro Oversize", category: "accesorios", price: 15.99, badge: "NUEVO", hue: 320, rating: 4.6, proof: "Recién llegado", tagline: "El cat-eye diva que da vibe mob wife glam al instante.", seo: "Gafas de sol cat-eye oversize retro, el modelo femenino y elegante para un look mob wife u old money. Aesthetic vintage viral. Foto de verano top." },
  { id: "phone-strap-cuentas-movil", name: "Colgante Móvil Phone Strap Cuentas", category: "accesorios", price: 11.99, hue: 300, rating: 4.6, proof: "El más buscado", tagline: "El phone charm de cuentas que personaliza y lleva el móvil sin manos.", seo: "Colgante de móvil (phone strap) de cuentas para llevar el teléfono cruzado y personalizarlo. El accesorio DIY viral que combina con el bag charm." },
  { id: "bolso-mini-top-handle", name: "Bolso Mini Top-Handle Estructurado", category: "accesorios", price: 25.99, hue: 280, rating: 4.6, proof: "Favorito del mes", tagline: "El top-handle lady-bag que eleva el outfit con vibe old money.", seo: "Bolso mini de asa superior estructurado, el bolso lady-like pulido para un look elegante old money. Aesthetic clean girl viral que eleva el outfit." },
  { id: "rinonera-pecho-chest-rig", name: "Riñonera de Pecho Crossbody Utility", category: "accesorios", price: 19.99, hue: 200, rating: 4.6, proof: "Lo más guardado", tagline: "El chest rig gorpcore hands-free que petó en los festival looks.", seo: "Riñonera de pecho crossbody utility, el bolso técnico hands-free de estética streetwear/gorpcore para festivales y ciudad. Tendencia viral 2026." },
  { id: "bolso-crochet-granny-square", name: "Bolso Tejido Crochet Granny Bag", category: "accesorios", price: 22.99, hue: 35, rating: 4.6, proof: "El más buscado", tagline: "El granny square bag boho con vibe artesanal coastal de verano.", seo: "Bolso de ganchillo crochet (granny square), el bolso boho artesanal de verano para un look coastal y cottagecore. Aesthetic hecho a mano viral." },
  { id: "set-rizador-heatless-curls", name: "Set Rizador Sin Calor Heatless Curls", category: "selfcare", price: 17.99, badge: "VIRAL", hue: 318, rating: 4.7, proof: "Viral en TikTok", tagline: "Ondas perfectas mientras duermes, sin plancha y sin dañar el pelo.", seo: "Set de rizador sin calor (heatless curls) de satén para dormir: consigue ondas perfectas sin dañar el pelo mientras descansas. El hack de pelo viral 2026." },
  { id: "cinta-pelo-lazo-saten-ribbon", name: "Cinta de Pelo Lazo Satén Largo Ribbon", category: "selfcare", price: 9.99, hue: 330, rating: 4.6, proof: "El más buscado", tagline: "El truco coquette de 5 segundos: un lazo de satén que eleva la coleta.", seo: "Cinta de pelo tipo lazo de satén largo (hair ribbon), el upgrade coquette más fácil para elevar una coleta. Aesthetic balletcore viral. Pack de colores." },
  { id: "pinza-garra-mate-neutra", name: "Pinza Garra Mate Neutra Clean Girl", category: "selfcare", price: 10.99, hue: 35, rating: 4.6, proof: "Lo más guardado", tagline: "La claw clip mate clean girl para un recogido effortless y elegante.", seo: "Pinza de pelo garra mate en tonos neutros (beige/marrón), el accesorio clean girl para un recogido effortless y elegante. Aesthetic minimal viral." },
  { id: "pinza-pelo-flor-3d", name: "Pinza Pelo Flor 3D Escultórica", category: "selfcare", price: 11.99, hue: 320, rating: 4.6, proof: "Favorito del mes", tagline: "La pinza flor 3D statement que destaca en cualquier peinado.", seo: "Pinza de pelo con flor 3D escultórica, el accesorio statement fashion-forward para un toque artístico y coquette. Tendencia de pelo viral 2026." },
  { id: "set-pinzas-perla-mini", name: "Set Pinzas Pelo Perla Mini Pearl Pins", category: "selfcare", price: 9.99, hue: 300, rating: 4.6, proof: "El más buscado", tagline: "Las pearl pins de bailarina: detalle delicado para peinados aesthetic.", seo: "Set de mini pinzas y horquillas de perlas, detalle balletcore elegante y atemporal para decorar el peinado. Aesthetic coquette viral. Pack variado." },
  { id: "gorro-beanie-lazo-coquette", name: "Gorro Beanie Punto con Lazo Coquette", category: "accesorios", price: 13.99, badge: "TRENDING", hue: 330, rating: 4.6, proof: "Tendencia 2026", tagline: "El bow beanie coquette que completa el OOTD de frío.", seo: "Gorro beanie de punto con lazo coquette, complemento de invierno cálido y femenino que completa el OOTD aesthetic. Tendencia viral 2026. Combinable." },
  { id: "banda-ancha-knot-headband", name: "Turbante / Banda Ancha Pelo Knot", category: "accesorios", price: 11.99, hue: 290, rating: 4.6, proof: "El más buscado", tagline: "El knot headband pija que viste el pelo al instante.", seo: "Banda ancha de pelo con nudo (knot headband), accesorio old money/clean girl para un look pulido y favorecedor. Aesthetic pija viral." },
  { id: "diadema-lazo-saten-gigante", name: "Diadema Lazo Satén Gigante Bow Band", category: "accesorios", price: 12.99, hue: 335, rating: 4.6, proof: "Lo más guardado", tagline: "El lazo gigante en la cabeza con vibe princesa coquette.", seo: "Diadema con lazo de satén gigante (bow headband), el accesorio coquette statement que convierte cualquier peinado en romántico. Aesthetic viral 2026." },
  { id: "conjunto-loungewear-punto-crema", name: "Conjunto Loungewear Punto Crema Set", category: "selfcare", price: 29.99, badge: "TRENDING", hue: 40, rating: 4.7, proof: "Tendencia 2026", tagline: "El matching lounge set crema: uniforme soft life para estar en casa con estilo.", seo: "Conjunto de loungewear de punto en tono crema (top + pantalón), el uniforme soft life clean girl para estar en casa con estilo. Aesthetic viral cozy." },
  { id: "pijama-corto-saten-cami-short", name: "Pijama Corto Satén Cami + Short", category: "selfcare", price: 22.99, hue: 320, rating: 4.6, proof: "El más buscado", tagline: "El silky PJ set coquette de las night routines aesthetic.", seo: "Pijama corto de satén (camiseta + short), conjunto sedoso coquette para una night routine femenina y elegante. Aesthetic soft girl viral. Tallas desde la S." },
  { id: "bata-fluffy-albornoz-suave", name: "Albornoz / Bata Suave Fluffy Robe", category: "selfcare", price: 26.99, hue: 300, rating: 4.6, proof: "Lo más guardado", tagline: "La fluffy robe de spa day que ancla tu rutina cozy de self-care.", seo: "Albornoz/bata súper suave y mullida (fluffy robe), la prenda cozy que ancla la rutina de spa en casa. Aesthetic self-care viral de otoño-invierno." },
  { id: "set-pijama-coquette-encaje", name: "Set Pijama Coquette Lazo + Encaje", category: "selfcare", price: 23.99, hue: 335, rating: 4.6, proof: "Favorito del mes", tagline: "El pijama princesa coquette con lazo y encaje para tu night routine.", seo: "Conjunto de pijama coquette con detalles de lazo y encaje, sleepwear romántico para sentirse princesa. Aesthetic balletcore viral. Tallas desde la S." },
  { id: "calcetines-volante-frilly", name: "Calcetines Volante Frilly Ruffle Socks", category: "accesorios", price: 9.99, badge: "VIRAL", hue: 320, rating: 4.6, proof: "Viral en TikTok", tagline: "Los frilly socks con bailarinas: el detalle coquette que define el look.", seo: "Calcetines tobilleros con volante (frilly socks) para lucir con bailarinas o Mary Janes, el detalle coquette que define el look. Aesthetic viral. Pack." },
  { id: "calcetines-mesh-glass-socks", name: "Calcetines Mesh Transparentes Glass Socks", category: "accesorios", price: 9.99, hue: 285, rating: 4.6, proof: "El más buscado", tagline: "Las glass socks de hada: calcetín transparente con sandalias y tacones.", seo: "Calcetines de malla transparente con borde de encaje (glass socks), toque delicado fairy-coquette en el tobillo. Aesthetic viral de verano. Pack variado." },
  { id: "calentadores-pierna-leg-warmers", name: "Calentadores de Pierna Punto Leg Warmers", category: "accesorios", price: 12.99, badge: "TRENDING", hue: 280, rating: 4.6, proof: "Tendencia 2026", tagline: "Los leg warmers de bailarina que definen el OOTD balletcore de frío.", seo: "Calentadores de pierna de punto (leg warmers), pieza central del balletcore 2026 para llevar sobre medias o vaqueros. Aesthetic bailarina viral." },
  { id: "medias-opacas-color-tights", name: "Medias Tupidas Color Opaque Tights", category: "accesorios", price: 11.99, hue: 350, rating: 4.5, proof: "Lo más guardado", tagline: "Las medias de color statement leg que visten un básico al instante.", seo: "Medias tupidas opacas de color (burdeos, marrón, butter), legwear statement para dar un toque de color al look. Tendencia viral 2026. Varias tallas." },
];

// Cada producto usa su foto real en /productos/{id}.jpg y una descripción SEO.
export const PRODUCTS: Product[] = RAW_PRODUCTS.map((p) => ({
  ...p,
  image: p.image ?? `/productos/${p.id}.jpg`,
  seo:
    p.seo ??
    `${p.name}: ${p.tagline} ${CATEGORY_MAP[p.category].name} viral y aesthetic de La TikiToki, con envío rápido a toda España. Lo viral, antes que nadie.`,
}));

export const FEATURED = PRODUCTS.filter((p) => p.featured);

export const BEST_SELLER = PRODUCTS.find((p) => p.bestSeller) ?? PRODUCTS[0];

export function productsByCategory(key: CategoryKey | "all") {
  if (key === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === key);
}
